# Generated by Django 4.2.8 on 2023-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(blank=True, to='shop_side.shop'),
        ),
    ]
